In [7]:
# 기본 모듈 임포트
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns 

import matplotlib.font_manager as fm 
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font",family=font_name)

mpl.rcParams["axes.unicode_minus"] = False

from sklearn.model_selection import train_test_split

#pip install mglearn
import mglearn      # 머신러닝 학습을 위한 모듈

ModuleNotFoundError: No module named 'mglearn'

# 1. 데이터 인코딩
    Label Encoding과 One-Hot Encoding
    
    
    https://2-chae.github.io/category/1.ai/30
    

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)

print("인코딩 클래스 : ", encoder.classes_)

labels = encoder.transform(items)
print("인코딩 변환값 : ", labels)

print('디코딩 원본값 : ', encoder.inverse_transform(labels))   

인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
인코딩 변환값 :  [0 1 4 5 3 3 2 2]
디코딩 원본값 :  ['TV' '냉장고' '전자렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [3]:
from sklearn.preprocessing import OneHotEncoder

In [5]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

labels = labels.reshape(-1, 1)
labels
oh = OneHotEncoder()
oh.fit(labels)
oh_labels = oh.transform(labels)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [9]:

# get_dummys와의 차이 : get_dummys는 판다스에서aks 제공하고 문자를 바로 숫자로 변경해주지만 
#반드시 데이터프레임 형태여야함
df = pd.DataFrame({'items': ['TV', '냉장고','전자렌지','선풍기','선풍기','믹서','믹서']})
df
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지
0         1          0         0          0           0
1         0          1         0          0           0
2         0          0         0          0           1
3         0          0         0          1           0
4         0          0         0          1           0
5         0          0         1          0           0
6         0          0         1          0           0

# 2. 피처 스케일링 (feature scaling)

스케일링 : 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업

스케일링에 영향 안 받는 친구들 : 트리계열 (디시전 트리, 랜덤포레스트 등)

https://2-chae.github.io/category/1.ai/31

    + 표준화(Standardization)
        -피처 각각의 평균이 0이고 분산이 1인 표준정규분포를 가진 값으로 변환
                           - 정규화가 안되면 표본을 마마마마마마많이 하면 중심극한정리로 표준화 됨
                           
    + 정규화(Nomalization)
        - 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념
        

### StandardScaler

StandardScaler는 표준화를 지원하기 위한 클래스이다. 즉, 가우시안 정규 분포를 가질 수 있도록 데이터를 변환한다. 특히 사이킷런에서 구현한 RBF 커널을 이용하는 SVM(Support Vector Machine), 선형 회귀(Linear Regression), 로지스틱 회귀(Logistic Regression)은 데이터가 가우시안 분포를 가진다는 가정하에 구현됐기에 사전에 표준화를 적용하는 건 성능 향상에 중요한 요소가 될 수 있다.

In [14]:
from sklearn.datasets import load_iris

iris = load_iris()

In [16]:
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [18]:
print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [20]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScaler
MinMaxScaler는 데이터값(최소, 최대)을 0과 1 사이의 범위 값으로 변환한다. (음수값이 있으면 -1~1 )

In [21]:

from sklearn.preprocessing import MinMaxScaler

In [22]:
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [23]:
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)

print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


# 교차 검증
    
    특정 머신러닝 알고리즘에서 최적으로 동작할 수 있도록 데이터를 선별해 학습한다면 실제 데이터 양식과는 많은 차이가 있을 것이고 결국 성능 저하로 이어질 수 있다.

교차 검증은 이런 데이터 편중을 막기 위해 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행하는 것이다. 데이터를 학습 데이터와 테스트 데이터 세트로 구분하고 학습 데이터는 다시 학습데이터 세트와 검증 데이터 세트로 나눈다.
    
        K-Fold Cross Validation
        KFold, StratifiedKFold
        
        
        https://2-chae.github.io/category/1.ai/28
        

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold

In [25]:

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

In [28]:
kfold  = KFold(n_splits=5)
cv_accuracy=[]
n_iter = 0


# KFold 객체의 split()을 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
#     print(train_index,test_index) : 첫번째 30개가 테스트, 2번째 30개가 테스트. ...눈으로 확인해보기
#     # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
 # 학습 및 예측
    
    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    
    # 반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    
    print('\n#{0} 교차 검증 정확도 :{1}, 학습데이터크기 :{2}, 검증데이터크기:{3}'.format(n_iter, accuracy, train_size, test_size))
    print('\n#{0}  검증 세트 인덱스:{1}'.format(n_iter, test_index))
    
    cv_accuracy.append(accuracy)
    


#1 교차 검증 정확도 :1.0, 학습데이터크기 :120, 검증데이터크기:30

#1  검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습데이터크기 :120, 검증데이터크기:30

#2  검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습데이터크기 :120, 검증데이터크기:30

#3  검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습데이터크기 :120, 검증데이터크기:30

#4  검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습데이터크기 :120, 검증데이터크기:30

#5  검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


In [29]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [30]:

kfold = KFold(n_splits=3)
n_iter=0

for train_idx, test_idx in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_idx]
    label_test = iris_df['label'].iloc[test_idx]
    
    print('\n## 교차 검증: {}'.format(n_iter))
    print('학습레이블 데이터 분포:\n', label_train.value_counts())
    print('검증레이블 데이터 분포:\n', label_test.value_counts())


## 교차 검증: 1
학습레이블 데이터 분포:
 2    50
1    50
Name: label, dtype: int64
검증레이블 데이터 분포:
 0    50
Name: label, dtype: int64

## 교차 검증: 2
학습레이블 데이터 분포:
 2    50
0    50
Name: label, dtype: int64
검증레이블 데이터 분포:
 1    50
Name: label, dtype: int64

## 교차 검증: 3
학습레이블 데이터 분포:
 1    50
0    50
Name: label, dtype: int64
검증레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [31]:
from sklearn.model_selection import StratifiedKFold

skfold = StratifiedKFold(n_splits=3)
n_iter=0

for train_idx, test_idx in skfold.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_idx]
    label_test = iris_df['label'].iloc[test_idx]
    
    print('\n## 교차 검증: {}'.format(n_iter))
    print('학습레이블 데이터 분포:\n', label_train.value_counts())
    print('검증레이블 데이터 분포:\n', label_test.value_counts())


## 교차 검증: 1
학습레이블 데이터 분포:
 2    34
1    33
0    33
Name: label, dtype: int64
검증레이블 데이터 분포:
 1    17
0    17
2    16
Name: label, dtype: int64

## 교차 검증: 2
학습레이블 데이터 분포:
 1    34
2    33
0    33
Name: label, dtype: int64
검증레이블 데이터 분포:
 2    17
0    17
1    16
Name: label, dtype: int64

## 교차 검증: 3
학습레이블 데이터 분포:
 0    34
2    33
1    33
Name: label, dtype: int64
검증레이블 데이터 분포:
 2    17
1    17
0    16
Name: label, dtype: int64


In [32]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)

cv_accuracy=[]
n_iter = 0

for train_index, test_index in skfold.split(features, label):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    
    print('\n#{0} {1}, {2}, {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증셋 인덱스:{1}'.format(n_iter, test_index))
    
    cv_accuracy.append(accuracy)
    
print('\n평균 검증 정확도:', np.mean(cv_accuracy))


#1 0.98, 100, 50
#1 검증셋 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 0.94, 100, 50
#2 검증셋 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 0.98, 100, 50
#3 검증셋 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

평균 검증 정확도: 0.9666666666666667


In [33]:

from sklearn.model_selection import cross_val_score

In [38]:

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target


scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('평균 정확도:', np.mean(scores))


평균 정확도: 0.9666666666666667


# GridSearchCV

    https://2-chae.github.io/category/1.ai/29

In [39]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [40]:
iris =load_iris()
train_x, test_x, train_y, test_y = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

In [45]:
params = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [46]:
# param_grid의 하이퍼 파라미터를 3개의 train, valid set fold로 나누어 테스트 진행
grid_dtree = GridSearchCV(dtree, param_grid=params, cv=3, refit=True, scoring= "accuracy")

In [48]:
# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(train_x, train_y)

GridSearchCV(cv=3, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]},

In [50]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000997  3.371748e-07         0.000000         0.00000   
1       0.000333  4.703588e-04         0.000332         0.00047   
2       0.000332  4.701340e-04         0.000000         0.00000   
3       0.000333  4.702464e-04         0.000332         0.00047   
4       0.000333  4.702464e-04         0.000000         0.00000   
5       0.000000  0.000000e+00         0.000333         0.00047   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [51]:
scores_df=pd.DataFrame(grid_dtree.cv_results_)

scores_df[['params','mean_test_score', 'rank_test_score']]

params  mean_test_score  rank_test_score
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1

In [52]:
print("최적 파라미터 : ", grid_dtree.best_params_)
print("최적 정확도 : ", grid_dtree.best_score_)

최적 파라미터 :  {'max_depth': 3, 'min_samples_split': 2}
최적 정확도 :  0.975


In [55]:

estimator = grid_dtree.best_estimator_

pred = estimator.predict(test_x)
print('테스트 정확도 : ',accuracy_score(test_y, pred))

테스트 정확도 :  0.9666666666666667
